var myName = document.getElementById('name');
var designation = document.getElementById('designation');
var phone = document.getElementById('phone');
var email = document.getElementById('email');
var address = document.getElementById('address');
var passingyear = document.getElementById('passingyear');
var degree = document.getElementById('degree');
var institution = document.getElementById('institution');
var skills = document.getElementById('skills');
var language = document.getElementById('language');
var startyear = document.getElementById('startyear');
var endyear = document.getElementById('endyear');
var company = document.getElementById('company');
var companylocation = document.getElementById('companylocation');
var jobtitle = document.getElementById('jobtitle');
var responsibilities = document.getElementById('responsibilities');
var submitbtn = document.getElementById('submitbtn');
var form = document.getElementById('form');
console.log(myName, designation, phone, email, address, passingyear, degree, institution, skills, language, startyear, endyear, company, companylocation, jobtitle, responsibilities, submitbtn, form);
form === null || form === void 0 ? void 0 : form.addEventListener('submit', function (e) {
    e.preventDefault();
    localStorage.setItem("myname", myName.value);
    localStorage.setItem("designation", designation.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("address", address.value);
    localStorage.setItem("passingyear", passingyear.value);
    localStorage.setItem("degree", degree.value);
    localStorage.setItem("institution", institution.value);
    localStorage.setItem("skills", skills.value);
    localStorage.setItem("language", language.value);
    localStorage.setItem("startyear", startyear.value);
    localStorage.setItem("endyear", endyear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("companylocation", companylocation.value);
    localStorage.setItem("jobtitle", jobtitle.value);
    localStorage.setItem("responsibilities", responsibilities.value);
});
